# Generated by Django 6.1.1 on 2026-10-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('DISPONIBLE', 'Disponible'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=15)),
                ('visibilidad', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasenia', models.CharField(max_length=128)),
                ('habilitado', models.BooleanField(default=True)),
                ('rol_principal', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CONGELADA', 'Congelada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_matriculados', to='byteclass.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='byteclass.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_calificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CALIFICADA', 'Calificada'), ('CORREGIDA_MANUAL', 'Corregida Manualmente')], default='PENDIENTE', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('numero_intento', models.PositiveSmallIntegerField(default=1)),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='byteclass.evaluacion')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_entregadas', to='byteclass.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('MULTIPLE', 'Selección Múltiple'), ('VERDADERO_FALSO', 'Verdadero o Falso'), ('ABIERTA', 'Desarrollo / Abierta')], default='MULTIPLE', max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='byteclass.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='byteclass.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_abierto', models.TextField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('id_entrega_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='byteclass.entregaevaluacion')),
                ('id_opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_seleccionadas', to='byteclass.opcion')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_alumnos', to='byteclass.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('visibilidad', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='byteclass.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto / Lectura'), ('VIDEO', 'Video'), ('ARCHIVO', 'Documento / Archivo descargable')], default='TEXTO', max_length=10)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='lecciones_archivos/')),
                ('visibilidad', models.BooleanField(default=True)),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='byteclass.seccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='byteclass.seccion'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('id_registro_modificado', models.PositiveIntegerField()),
                ('estado_anterior', models.JSONField(blank=True, null=True)),
                ('estado_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to='byteclass.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='byteclass.curso')),
                ('id_usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='byteclass.usuario')),
                ('id_usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='byteclass.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fechahora_salida', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='byteclass.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_impartidos', to='byteclass.usuario'),
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('cantidad_accesos', models.PositiveIntegerField(default=0)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='byteclass.leccion')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_lecciones', to='byteclass.matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_matricula', 'id_leccion'), name='unique_progreso_leccion')],
            },
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('id_estudiante', 'id_curso'), name='unique_matricula_estudiante_curso'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('codigo', 'periodo'), name='unique_curso_periodo'),
        ),
    ]
